create sequence hibernate_sequence start with 1 increment by 1;

create table book (id bigint generated by default as identity, course varchar(255), isbn varchar(13) not null, title varchar(128) not null, primary key (id));
create table book_authors (book_id bigint not null, authors varchar(255));
create table book_sellers (book_id bigint not null, sellers_id bigint not null);
create table message (id bigint generated by default as identity, content varchar(800) not null, recipient bigint not null, sender bigint not null, timestamp timestamp, primary key (id));
create table user (id bigint generated by default as identity, email varchar(255) not null, first_name varchar(28) not null, last_name varchar(28) not null, password varchar(255) not null, primary key (id));
create table user_books_for_sale (user_id bigint not null, books_for_sale_id bigint not null);
alter table book_authors add constraint FKs4xm7q8i3uxvaiswj1c35nnxw foreign key (book_id) references book;
alter table book_sellers add constraint FKtjck6i5th3idi2e4obvxqe45b foreign key (sellers_id) references user;
alter table book_sellers add constraint FKkmpxn70jr7stgmufer2lfsafp foreign key (book_id) references book;
alter table user_books_for_sale add constraint FKlm4031tvx5l8vn0e0o2txk339 foreign key (books_for_sale_id) references book;
alter table user_books_for_sale add constraint FKnxivul834ewl07sv5up17rqot foreign key (user_id) references user;